### ISSUE TITLE
Wildcards not supported?

### ISSUE THREAD

**Issue by sanderheilbron** [chrisakroyd/robots-txt-parser#1]
Several search engine bots support wildcards.

I've checked this for the following robots.txt files, and noticed that robots-txt-parser seems like to ignore this for the following robots txt files:
https://www.zalando.nl/robots.txt
https://www.bcc.nl/robots.txt

But supports it for the following robots txt file:
https://www.karwei.nl/robots.txt

Hope you could do a check to see what is causing this behaviour.

**Comment by ChristopherAkroyd** [comment]
Thanks for bringing this to my attention, I'm looking into it now and I should hopefully have a fix out over the coming days.

**Comment by keyndark** [comment]
Hi. did you have fix for this? Thanks!

**Comment by ChristopherAkroyd** [comment]
Hey keyndark, I managed to get tests running that confirmed the issue but I haven't managed to fix one edge case. I'm aiming to have a fix done for Friday this week but that timeline may change.
