### ISSUE TITLE
Project maintained?

### ISSUE THREAD

**Issue by abhisheksurve45** [chrisakroyd/robots-txt-parser#14]
Is this project currently maintained?

If not, what could be the best approach to have a robots txt parser?

Google has released its parser https://github.com/google/robotstxt/tree/master however is in C++ :-(

Looking for something in Go,Java or JS.

**Comment by chrisakroyd** [comment]
Will work on maintenance either this week or next weekend, been meaning to do the bug fix pass so I'll take your issue as inspiration.

**Comment by abhisheksurve45** [comment]
Thanks @chrisakroyd
